### ISSUE TITLE
Stopped working with Julia 0.6

### ISSUE THREAD

**Issue by shhong** [JuliaComputing/ArrayFire.jl#155] opened 2017-06-20 05:00 UTC
I just updated to Julia 0.6 and ArrayFire stopped working as follows

julia> using ArrayFire

WARNING: deprecated syntax "typealias AFVector{T} AFArray{T,1}" at /Users/shhong/.julia/v0.6/ArrayFire/src/ArrayFire.jl:20.
Use "AFVector{T} = AFArray{T,1}" instead.

WARNING: deprecated syntax "typealias AFMatrix{T} AFArray{T,2}" at /Users/shhong/.julia/v0.6/ArrayFire/src/ArrayFire.jl:21.
Use "AFMatrix{T} = AFArray{T,2}" instead.

WARNING: deprecated syntax "inner constructor AFArray(...) around /Users/shhong/.julia/v0.6/ArrayFire/src/ArrayFire.jl:13".
Use "AFArray{T,N}(...) where {T,N}" instead.

WARNING: deprecated syntax "typealias dim Int" at /Users/shhong/.julia/v0.6/ArrayFire/src/defns.jl:78.
Use "const dim = Int" instead.
WARNING: Base.LinearIndexing is deprecated, use Base.IndexStyle instead.
  likely near /Users/shhong/.julia/v0.6/ArrayFire/src/indexing.jl:125
ERROR: LoadError: LoadError: UndefVarError: af_array not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] _require(::Symbol) at ./loading.jl:483
 [6] require(::Symbol) at ./loading.jl:398
while loading /Users/shhong/.julia/v0.6/ArrayFire/src/wrap.jl, in expression starting on line 1581
while loading /Users/shhong/.julia/v0.6/ArrayFire/src/ArrayFire.jl, in expression starting on line 25

I am using Mac OS X 10.12.5 and ArrayFire 3.4.2.

**Comment by oschulz** [comment] 2017-06-20 15:32
I'd love to see ArrayFire work with v0.6 as well.

**Comment by ranjanan** [comment] 2017-06-20 16:00
@shhong @oschulz There's an excellent PR which @gaika has submitted ( #121 ) which he's getting ready to make ArrayFire work with v0.6. Perhaps you can speed along the process by helping him with his PR.

**Comment by gaika** [comment] 2017-06-20 16:37
#121 works fine with Julia v0.6. Need more tests to cover areas that I'm less familiar with but otherwise it is stable.

**Comment by oschulz** [comment] 2017-06-20 19:32
Thanks, I'll try it out!

**Comment by oschulz** [comment] 2017-06-20 19:33
@gaika Looks great! Can I help with anything specific (I'm not an ArrayFire expert, though)?

**Comment by gaika** [comment] 2017-06-20 19:45
@oschulz: Need tests that compare the results of native Julia functions with corresponding ArrayFire functions. In the ideal world `AFArray` should be a drop-in replacement for a regular `Array`, right now that is true only for a small (important for me) subset of operations.

 If you can write tests for the functions that are important for you I can make the implementation match your expectations. Got sparse array support in exactly that way.

**Comment by oschulz** [comment] 2017-06-20 19:59
@ranjanan, @gaika: Would it be possible to have the rewrite (#121) as a branch in the official ArrayFire repo? That would make it easier for people to try it out via, e.g.,  `Pkg.checkout("ArrayFire", "rewrite")`.

**Comment by hayatoikoma** [comment] 2017-07-20 19:22
@ranjanan , @gaika 
Considering the less activity on this repo and we cannot even import this library on v0.6. can I assume that this original package no longer maintained?

I am also happy to contribute to and use #121 if it is going to be maintained for a long time toward Julia v1.0. It would be great if @gaika can rewrite README to let us understand the current situation. Since nothing is documented, it is difficult to understand the current capability and its future plan.

**Comment by ranjanan** [comment] 2017-07-20 19:25
@hayatoikoma Yes, I am hoping to merge #121 as soon as possible to support v0.6. Perhaps I or @gaika can update the README to reflect that.

**Comment by gaika** [comment] 2017-07-20 19:39
I'm working on fixing the last issues that block the merge.

**Comment by oschulz** [comment] 2017-07-20 20:43
@hayatoikoma: I'm currently using @gaika's master branch (which is further along than this PR, because PR's based on a master don't auto-update), and it has worked quite well for me so far.

**Comment by gaika** [comment] 2017-07-21 11:06
Thanks @hayatoikoma  and @oschulz  it is mostly ready. Some docs are out of date, more tests are welcome (current coverage is only 40%).

**Comment by gaika** [comment] 2017-07-22 10:00
I'd say it is ready to merge, just backported all bugfixes.

**Comment by 4lrdyD** [comment] 2017-08-02 14:20
Hello, I need to work with ArrayFire in Julia 0.6, but not run Pkg.test, I cheked #121 but I don't know what to do with that, i'm confused.

**Comment by musm** [comment] 2017-08-02 15:34
@4lrdyD #121  will be merged pretty soon from what I gather in this thread

**Comment by gaika** [comment] 2017-09-13 10:00
merged with [v0.1.0](https://github.com/JuliaComputing/ArrayFire.jl/releases/tag/v0.1.0)

**Closed by gaika** 2017-09-13 10:00 UTC

**Comment by 4lrdyD** [comment] 2017-09-17 06:25
sorry, I do not know if I should ask here, but should I install the latest version of ArrayFire to work? I still have errors with Pkg.test

**Comment by gaika** [comment] 2017-09-19 00:42
@4lrdyD What errors do you see? What is your backend?

**Comment by 4lrdyD** [comment] 2017-09-19 03:51
Error during the test:

**julia> Pkg.test("ArrayFire")**
INFO: Testing ArrayFire
ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
[0] NVIDIA  : GeForce GT 630M, 2048 MB
-1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
-2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB
Main: Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: ArgumentError: Module AutoDiffSource not found in current path.
  Run `Pkg.add("AutoDiffSource")` to install the AutoDiffSource package.
  Stacktrace:
   [1] _require(::Symbol) at .\loading.jl:428
   [2] require(::Symbol) at .\loading.jl:398
   [3] include_from_node1(::String) at .\loading.jl:569
   [4] include(::String) at .\sysimg.jl:14
   [5] macro expansion at C:\Users\user\.julia\v0.6\ArrayFire\test\runtests.jl:11 [inlined]
   [6] macro expansion at .\test.jl:860 [inlined]
   [7] anonymous at .\<missing>:?
   [8] include_from_node1(::String) at .\loading.jl:569
   [9] include(::String) at .\sysimg.jl:14
   [10] process_options(::Base.JLOptions) at .\client.jl:305
   [11] _start() at .\client.jl:371
  while loading C:\Users\user\.julia\v0.6\ArrayFire\test\autodiff.jl, in expression starting on line 1
Test Summary:        | Pass  Error  Total
Main                 |  305      1    306
  Scope              |    1             1
  Indexing           |    4             4
  Inplace assignment |   10            10
  Sparse             |    7             7
  Math               |   32            32
  Arrays             |   36            36
  Sizes              |   12            12
  abs                |    1             1
  acos               |    1             1
  asin               |    1             1
  atan               |    1             1
  cbrt               |    1             1
  ceil               |    1             1
  cos                |    1             1
  cosh               |    1             1
  exp                |    1             1
  expm1              |    1             1
  factorial          |    1             1
  floor              |    1             1
  erfc               |    1             1
  imag               |    1             1
  isinf              |    1             1
  isnan              |    1             1
  lgamma             |    1             1
  log                |    1             1
  log10              |    1             1
  log1p              |    1             1
  log2               |    1             1
  real               |    1             1
  round              |    1             1
  sign               |    1             1
  signbit            |    1             1
  sin                |    1             1
  sinh               |    1             1
  sqrt               |    1             1
  tan                |    1             1
  tanh               |    1             1
  trunc              |    1             1
  identity           |    1             1
  cov                |    1             1
  vec                |    1             1
  zeros              |    1             1
  ones               |    1             1
  transpose          |    1             1
  maximum            |    1             1
  minimum            |    1             1
  sum                |    1             1
  prod               |    1             1
  sizeof             |    1             1
  var                |    1             1
  std                |    1             1
  mean               |    1             1
  median             |    1             1
  Sort               |    2             2
  IR                 |    2             2
ERROR: LoadError: Some tests did not pass: 305 passed, 0 failed, 1 errored, 0 broken.
while loading C:\Users\user\.julia\v0.6\ArrayFire\test\runtests.jl, in expression starting on line 5

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffccf130e01 -- RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
while loading no file, in expression starting on line 0
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
clGetExtensionFunctionAddress at C:\WINDOWS\System32\nvopencl.dll (unknown line)
clGetExtensionFunctionAddress at C:\WINDOWS\System32\nvopencl.dll (unknown line)
clGetExtensionFunctionAddress at C:\WINDOWS\System32\nvopencl.dll (unknown line)
clGetExtensionFunctionAddress at C:\WINDOWS\System32\nvopencl.dll (unknown line)
clGetExtensionFunctionAddress at C:\WINDOWS\System32\nvopencl.dll (unknown line)
clGetExtensionFunctionAddress at C:\WINDOWS\System32\nvopencl.dll (unknown line)
af::translate at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::translate at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::translate at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::translate at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::translate at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::translate at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::ycbcr2rgb at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::ycbcr2rgb at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
af::ycbcr2rgb at C:\Program Files\ArrayFire\v3\lib\afopencl.dll (unknown line)
RtlDeactivateActivationContextUnsafeFast at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
LdrShutdownProcess at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlExitUserProcess at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
FatalExit at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
exit at C:\WINDOWS\System32\msvcrt.dll (unknown line)
initterm_e at C:\WINDOWS\System32\msvcrt.dll (unknown line)
jl_exit at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\jl_uv.c:552
_start at .\client.jl:419
unknown function (ip: 0000000061CDF45E)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1424 [inlined]
true_main at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:127
wmain at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:264
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.2-1/crt\crtexe.c:329
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.2-1/crt\crtexe.c:212
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 11864286 (Pool: 11860723; Big: 3563); GC: 24
==============================[ ERROR: ArrayFire ]==============================

failed process: Process(`'C:\Users\user\AppData\Local\Julia-0.6.0\bin\julia.exe' -Cx86-64 '-JC:\Users\user\AppData\Local\Julia-0.6.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\user\.julia\v0.6\ArrayFire\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
ERROR: ArrayFire had test errors

I tried install ** AutoDiffSource ** but i got an error too, and I reported them in https://github.com/gaika/AutoDiffSource.jl/issues/17

**Comment by gaika** [comment] 2017-09-19 04:18
Thanks for catching it, I've added AutoDiffSource as a dependency for tests in 44a6a8d7d15a4b3e0928e619797ff42a96ad65be
