### ISSUE TITLE
Test Failed

### ISSUE THREAD

**Issue by aw2018** [JuliaComputing/ArrayFire.jl#203] opened 2018-04-05 15:52 UTC
I got 1 error in the testing ArrayFire as detailed below, and did not know why. Any ideas for that?
In addition, how to use extra functions like functions importing from python scipy.stats in ArrayFire? Thanks
 
Pkg.test("ArrayFire")
INFO: Testing ArrayFire
ArrayFire v3.5.1 (CUDA, 64-bit Linux, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: 375.39
[0] Tesla K40m, 11440 MB, CUDA Compute 3.5
-1- Tesla K40m, 11440 MB, CUDA Compute 3.5
Main: Test Failed
  Expression: mean(amf) == mean(am)
   Evaluated: 0.3927531f0 == 0.39275306f0
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] macro expansion at /home/aw/.julia/v0.6/ArrayFire/test/runtests.jl:9 [inlined]
 [4] macro expansion at ./test.jl:860 [inlined]
 [5] anonymous at ./<missing>:?
Test Summary:        | Pass  Fail  Total
Main                 |  340     1    341
  Scope              |    1            1
  Indexing           |    4            4
  Inplace assignment |   10           10
  Sparse             |    7            7
  Math               |   32           32
  Arrays             |   36           36
  Sizes              |   12           12
  abs                |    1            1
  acos               |    1            1
  asin               |    1            1
  atan               |    1            1
  cbrt               |    1            1
  ceil               |    1            1
  cos                |    1            1
  cosh               |    1            1
  exp                |    1            1
  expm1              |    1            1
  factorial          |    1            1
  floor              |    1            1
  erfc               |    1            1
  imag               |    1            1
  isinf              |    1            1
  isnan              |    1            1
  lgamma             |    1            1
  log                |    1            1
  log10              |    1            1
  log1p              |    1            1
  log2               |    1            1
  real               |    1            1
  round              |    1            1
  sign               |    1            1
  signbit            |    1            1
  sin                |    1            1
  sinh               |    1            1
  sqrt               |    1            1
  tan                |    1            1
  tanh               |    1            1
  trunc              |    1            1
  identity           |    1            1
  cov                |    1            1
  vec                |    1            1
  zeros              |    1            1
  ones               |    1            1
  transpose          |    1            1
  maximum            |    1            1
  minimum            |    1            1
  sum                |    1            1
  prod               |    1            1
  sizeof             |    1            1
  var                |    1            1
  std                |    1            1
  mean               |    1            1
  median             |    1            1
  Sort               |    2            2
  IR                 |    2            2
  Autodiff           |   36           36
ERROR: LoadError: Some tests did not pass: 340 passed, 1 failed, 0 errored, 0 broken.
while loading /home/aw/.julia/v0.6/ArrayFire/test/runtests.jl, in expression starting on line 5
==============================================[ ERROR: ArrayFire ]==============================================

failed process: Process(`/home/aw/julia/usr/bin/julia -Cx86-64 -J/home/aw/julia/usr/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/aw/.julia/v0.6/ArrayFire/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================================================
ERROR: ArrayFire had test errors

**Comment by gaika** [comment] 2018-04-05 16:34
seems to be a rounding error or https://github.com/arrayfire/arrayfire/issues/2093

**Comment by aw2018** [comment] 2018-04-05 17:05
@gaika 
Thanks for your response. How to fix it? It passed the testing in another user account, but failed the testing in my account in the same cluster. It is also working for most of functions, but killed and exited julia when call this function svd(a).

**Comment by aw2018** [comment] 2018-04-05 19:50
@gaika 
It is working now after correcting its path. My next question is how to use the extra function like corspearman from StatsBase. corspearman works very well in CPU, but failed in ArrayFire under GPU. Example below,
a = rand(10, 10)
ad = AFArray(a)

corspearman(a[1,:],a[2,:])  ##working under CPU
0.05454545454545454   

corspearman(ad[1,:],ad[2,:]) ##FAILED IN ARRAYFIRE
ERROR: MethodError: no method matching create_seq(::Base.Slice{Base.OneTo{Int64}})
Closest candidates are:
  create_seq(::Colon) at /home/aw/.julia/v0.6/ArrayFire/src/indexing.jl:27
  create_seq(::Int64) at /home/aw/.julia/v0.6/ArrayFire/src/indexing.jl:26
  create_seq(::UnitRange) at /home/aw/.julia/v0.6/ArrayFire/src/indexing.jl:24
  ...
Stacktrace:
 [1] set_indexer!(::Ptr{ArrayFire.af_index_t}, ::Int64, ::Base.Slice{Base.OneTo{Int64}}) at /home/aw/.julia/v0.6/ArrayFire/src/indexing.jl:29
 [2] create_indexers(::Tuple{Base.Slice{Base.OneTo{Int64}},Int64}) at /home/aw/.julia/v0.6/ArrayFire/src/indexing.jl:61
 [3] getindex(::ArrayFire.AFArray{Float64,2}, ::Base.Slice{Base.OneTo{Int64}}, ::Int64) at /home/aw/.julia/v0.6/ArrayFire/src/indexing.jl:68
 [4] mapslices(::StatsBase.#tiedrank, ::ArrayFire.AFArray{Float64,2}, ::Array{Int64,1}) at ./abstractarray.jl:1804
 [5] mapslices(::Function, ::ArrayFire.AFArray{Float64,2}, ::Int64) at ./abstractarray.jl:1785
 [6] corspearman(::ArrayFire.AFArray{Float64,2}, ::ArrayFire.AFArray{Float64,2}) at /home/aw/.julia/v0.6/StatsBase/src/rankcorr.jl:22

**Comment by gaika** [comment] 2018-04-16 01:15
`mapslices` is not supported, duplicate of https://github.com/JuliaComputing/ArrayFire.jl/issues/187

**Closed by gaika** 2018-04-16 01:15 UTC
